### ISSUE TITLE
Can't migrate Close Date

### ISSUE THREAD

**Issue by AmitNaveh23** [solidify/jira-azuredevops-migrator#117]
Is It possible to migrate close date like created date ?
I tried several ways but nothing worked

**Comment by madkoo** [comment]
Hi, @AmitNaveh23  can you give more context what you are trying to accomplish?

**Comment by AmitNaveh23** [comment]
Sure, I attached a screenshot.
![closeddate](https://user-images.githubusercontent.com/54633588/69712981-68938700-110c-11ea-9de4-b201f3db532a.PNG)

When importing, the closed date is set to the current import time instead of the real closed date from Jira. It's also happening in "Closed by" which is set to my name (whoever is doing the import) instead of the real person who closed that bug in Jira

**Comment by madkoo** [comment]
@AmitNaveh23. We have investigated this case and what we found was that ADO by default does not allow us to edit ClosedDate. On save it is using the server clock time and that is why you see the current Date time in the closed date field. As this is the default behavior in ADO we will keep it as it is for the time being.
About the "ClosedBy" field that one can be updated with the correct value from Jira when importing and that will be fixed in the next release.

**Comment by MOlausson** [comment]
Fixed from v.2.2.88

**Comment by MOlausson** [comment]
Fixed in 2.3.1.

**Comment by AmitNaveh23** [comment]
Still doesn't work for me... 
Should I configure something for it ?

![image](https://user-images.githubusercontent.com/54633588/69973026-66299680-152b-11ea-9ce5-95a43ed76ca5.png)

**Comment by AmitNaveh23** [comment]
@madkoo  
I was able to do it by a script, updating work item with bypass_rules=True

 result = wit_client.update_work_item(patch_document, itemId, project_name, validate_only=False, bypass_rules=True)

can it be done in your side?
