### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by MOlausson** [solidify/jira-azuredevops-migrator#139]
If duplicate Target mapping exist in the configuration file the export fails to start with the above error. 

Proposed solution: handle error and report as a warning that this is probably something that should be addressed by the user running the migration.

**Comment by MOlausson** [comment]
Fixed in v2.3.10.

**Comment by runerasmussen** [comment]
Hi, I am still experiencing this issue in v2.3.10 unfortunately. Please see details which I posted in Pull Request #140
