### ISSUE TITLE
User mapping works with intermittent issues

### ISSUE THREAD

**Issue by zarkolazarov** [solidify/jira-azuredevops-migrator#210]
Using the latest version Solidify Migrator Tool 2.3.79, Jira Atlassian Cloud, Azure DevOps.

To map the users we had to reconfigure the users mapping file.
In previous version of the tool we could use:
Some.JiraUser@domain.com=Some.AzureDevOpsUser@domain.com

Latest version we have to use:
JiraAccountID=Some.AzureDevOpsUser@domain.com

This way,
- some of the tickets migrate as unassigned
- In the ticket's comments section some users have their Jira ID instead of username
- in the ticket's history section some users have their Jira ID instead of username.

This is a sample of a warning in the export log:
[W][13:45:27] User with '8edfd27a2bc1429bb961437e2b57f300' not found in Jira, using usernameOrAccountId '8edfd27a2bc1429bb961437e2b57f300' for mapping. Using accountId instead.

Need to mention that user mapping like Some.JiraUser@domain.com=Some.AzureDevOpsUser@domain.com 
does not work for us.

**Comment by madkoo** [comment]
@zarkolazarov the reason why  "Some.JiraUser@domain.com=Some.AzureDevOpsUser@domain.com" user mapping does not work is related to Jira Cloud API changes. Due to GDPR, they have changed what data can be requested. 
To get a user email address then the user needs to allow that from their profile.

As I understand you have changed the user mapping to "JiraAccountID=Some.AzureDevOpsUser@domain.com" and then ran the migration tool and had problems in the bullet list?

**Comment by marioberberyan** [comment]
@madkoo  Thanks for the answer. Me and my colleague Zarko has made the changes but still get an error when trying to get JIRA users using the "Jira.Users.GetUserAsync(usernameOrAccountId)" method on row 332 in JIRAProvider.cs in "jira-export" project (see the screenshot [in the link](https://prnt.sc/rwbl0p)):

"_The 'accountId' query parameter needs to be provided"_

Strange enough I get the same error when I`m using Postman to double check whether it`s working via API calls - the error is because I set the query param as "accountid" (notice the small "i"). 
Once I`ve changed the query param to "accountId" (with capital I) I started fetching JIRA user details.
Here`s the API call: https://melontech.atlassian.net/rest/api/latest/user?accountId=[MyAccountId]

Is there any chance the Atlassian.JIRA.dll has an issue with fetching users via account ids.

Thanks,
Mario

**Comment by zarkolazarov** [comment]
One more thing I would here:

What is difficult to troubleshoot is that some tickets have successful user mapping for user X and others have the the user's Jira AccountId shown instead of Display Name for the same user X.

If we check the jira exported json file for the ticket that has AccountId instead of Display name, the field ReferenceName": "System.AssignedTo" was completely missing.
But when getting ticket details for that ticket from the Jira API we receive the Assignee field with the user's e-mail address, meaning, it's not a privay issue with the Jira API in this case.

**Comment by madkoo** [comment]
@marioberberyan  thank you for your input, that is a good find. This indeed might be an SDK issue and we will look into this.

**Comment by marioberberyan** [comment]
@madkoo  that`s for the feedback. Let us know on your developments on this issue as it`s putting on hold our migration process for a huge number of projects.

Thanks,
Mario

**Comment by apiotuchAoD** [comment]
@madkoo I am also not getting user emails with 2.3.79. And I was getting them with 2.3.41 before but it looks like this is no longer the case.

**Comment by EdPerminas** [comment]
Any update on this fix going into a release?

**Comment by madkoo** [comment]
@EdPerminas  @apiotuchAoD  @ibrahimonder @marioberberyan @zarkolazarov 
We have released a new version that has fixed this problem. Also, we updated documentation regarding user mapping. In addition to that, we added a new config property to explicitly say if Jira Cloud or Jira Server is used.

**Comment by EdPerminas** [comment]
@madkoo can you please elaborate on how exactly users should be mapped for Jira Cloud?

Still getting a warning on Export: Specified user '00001:...-.....-....-.....-......' does not exist or you do not have required permissions, using accountId '00001:...-.....-....-.....-......'

And after that, when importing, assigned to imports as blank.

I've managed to get in usernames in exported files using various AccountID variations, but when importing - it still goes in to ADO as blank for assigned to field.

Also, when names in export were placed (next to Author), the command prompt was throwing same warnings as above.

**Comment by EdPerminas** [comment]
To add: it maps correct name to 'Created By' and 'Changed By'.

**Comment by madkoo** [comment]
@EdPerminas please take a look at the documentation, as it says there is that if you want to map with user email then to get the user email from Jira Cloud the specific user's email needs to be set to public in their profile, otherwise the tool falls back to using account id for mapping user.

**Comment by EdPerminas** [comment]
@madkoo are you referring to email visibility settings in System - General Configuration? Or is there another setting for this. As an admin I can't see something as 'set to public' in members profiles.

**Comment by madkoo** [comment]
@EdPerminas  It depends on how your users are managed, but at the moment I was referring to each user's profile where the mentioned setting is. 
Please take a look at the changes in Jira Cloud, in addition, you can find how user privacy can be managed : 
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

**Comment by EdPerminas** [comment]
@madkoo Right, I found the switches in my personal Jira account and switched everything to public. Same on organisational level. Got email in the exported file next to with no warnings on export. And then no warnings on import as well. Sadly, still AssignedTo set as blank.

Strange thing that exported file doesn't contain AssignedTo in the Field section. I took the mapping string for config file from the documentation:
{
"source": "assignee",
"target": "System.AssignedTo",
"mapper": "MapUser"
},

If in exported file I manually add under Fields:
{
          "ReferenceName": "System.AssignedTo",
          "Value": "Name.LastName@Domain.com"
 },

Then tool pushes the value with no problem.

**Comment by madkoo** [comment]
@EdPerminas  sounds strange because we haven't seen that case. Can you share your config and export log?

**Comment by prasathe-git** [comment]
I am also facing similar issue for AssignedTo, for around 12 items AssignedTo is set to blank. I have checked user file and I can find the entry of the user in the file.
Also the same user id has got properly assigned in other issues.

I am using version 2.3.85 for migration

**Comment by EdPerminas** [comment]
@madkoo before I share my config and export log files I found some interesting cases for Jira Cloud you may find useful:

- If I use Solidify with no users.txt, it copies in AssignedTo into Fields section in jsons (as AccountIDs)

- Same configuration, just adding the users.txt file in workfolder and it doesn't set AssignedTo at all as references in exported files

- There are cases when colleague did some work, left the team, and haven't set it's profile as public. Colleague's name can be visible as Assignee in Jira. I guess when code go through revisions, it will find it as missing username, and possibly somehow skip the assigned to reference?

**Comment by madkoo** [comment]
@EdPerminas , Interesting cases but we have not been able to reproduce these issues. That is the reason I have asked for the config and logs and how does your users.txt look like. 
As for the cases then if there is a history of setting an assignee, then in the export file, the value would be the account Id, if the email is not public and if there is no users.txt mapping set or if no match is found from the users.txt then the tool should log a warning and use the original value retrieved from the Jira issue.

**Comment by EdPerminas** [comment]
@madkoo sorry for replying just now. Here is my config files. I changed AccountIds and hidden the project names due to privacy sake. Just to make sure, all profiles are made public now and unfortunately I keep getting the same issue with blank assigned to.
